#!/bin/sh
set -e

check_trailing_whitespace() {
    git diff --cached --check --diff-filter=ACM --quiet || {
        echo "Trailing whitespace or whitespace errors found in staged changes."
        exit 1
    }
}

check_non_ascii_filenames() {
    allownonascii=$(git config --type=bool hooks.allownonascii)
    if [ "$allownonascii" = "true" ]; then
        return 0
    fi
    if git diff --cached --name-only --diff-filter=A -z | LC_ALL=C tr -d '[ -~]\0' | wc -c | grep -qv '^0$'; then
        echo "Error: Attempt to add a non-ASCII file name."
        echo "Use ASCII unless there is a clear reason for Unicode."
        exit 1
    fi
}

check_trailing_whitespace
check_non_ascii_filenames

exec make check
